# Generated by Django 3.2.8 on 2021-10-14 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211014_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ManyToManyField(default=None, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
