# Generated by Django 3.2.8 on 2021-10-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
