# Generated by Django 3.2.8 on 2021-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(default=None, related_name='listings', to='auctions.Category'),
        ),
    ]
