# Generated by Django 3.2.8 on 2021-10-15 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211015_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist_users',
            field=models.ManyToManyField(related_name='watchlist_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(default=None, related_name='category_listings', to='auctions.Category'),
        ),
    ]
