# Generated by Django 3.2.8 on 2021-10-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_watchlist_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
