# Generated by Django 4.0 on 2021-12-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run50', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_preference',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='run50.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run50.user')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.ImageField(blank=True, upload_to='activity_images')),
                ('elevation', models.IntegerField()),
                ('pace', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run50.user')),
            ],
        ),
    ]
