# Generated by Django 4.0 on 2021-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run50', '0002_user_share_preference_follower_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/default.png', upload_to='static'),
        ),
    ]
