# Generated by Django 4.0 on 2021-12-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run50', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
