# Generated by Django 4.0 on 2021-12-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run50', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='heart_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pace',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
