# Generated by Django 4.0 on 2021-12-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run50', '0005_alter_activity_elevation_alter_activity_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
