# Generated by Django 4.0 on 2021-12-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run50', '0008_alter_activity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
    ]
